---
authors:
  - "Gonzalo Rios @gonzariosm"
  - "Clemson Cheong @clemsonsitehost"
dependencies: {}
description: "Ansible Collection for SiteHost"
documentation: "https://kb.sitehost.nz/developers/sitehost-ansible-collection"
homepage: "https://github.com/sitehostnz/sitehost_ansible"
issues: "https://github.com/sitehostnz/sitehost_ansible/issues"
license_file: "COPYING"
name: cloud
namespace: sitehost
readme: README.md
repository: "https://github.com/sitehostnz/sitehost_ansible"
tags:
  - sitehost
  - cloud
<<<<<<< HEAD
version: 1.1.0
build_ignore: ["*.tar.gz", ".github", ".venv","test*",".vscode"]
=======
version: 1.2.0
build_ignore: ["*.tar.gz", ".github", ".venv","test*.*",".vscode"]
>>>>>>> 93cb381 (Started Cloud Container development.)
